### PR TITLE
Require isal on linux

### PR DESCRIPTION
**Pull request by rhpvorderman**
Wheels for isal are now build from version 0.3.0 onwards.
Installation is very quick.

### CODE REVIEW

**Comment by rhpvorderman** [comment]
Whoops. 3.5 is not supported anymore by python-isal. I also do not know how PyPy is going to behave with isal. Maybe it is possible to set more selectors to exclude pypy?

**Comment by marcelm** [comment]
We should remove Python 3.5 compatibility.

**Comment by rhpvorderman** [comment]
@marcelm Done. I also found the selector (`python_implementation`) to exclude PyPy when requiring python-isal.

**Comment by marcelm** [comment]
I only have a couple of minutes: Can you remove `py35` from `tox.ini` as well, please? Then you can merge yourself. If you do want to release v1.1.0, feel free to do so, just run `git tag v1.10 && git push --tags`.

**Comment by rhpvorderman** [comment]
Done. I also initiated the 1.1.0 release. I appreciate your trust in me. Thanks.

**Comment by marcelm** [comment]
I see this didn’t work. I guess we should run `twine check` as part of regular CI. It’s not annotated tag, so just delete it and re-tag whatever commit works.

**Comment by rhpvorderman** [comment]
Have done that. The release is now ready.

**Comment by marcelm** [comment]
> I did annotate the tag.

Ah ok, totally fine with me.

**Comment by rhpvorderman** [comment]
Yes, I also had to delete an annotated tag because of the twine upload failure. My apologies if this caused any unforeseen consequences.

**Pull request merged**
